### ISSUE TITLE
Workflow expression variable reference checks miss some variables

### ISSUE THREAD

**Issue by briantist** [github/vscode-github-actions#61] opened 2023-03-29 13:22 UTC
**Describe the bug**
The expression checker looks to see if variables that are referenced are actually defined and warns if a context reference may not be valid. This can cause bugs like #47 , but also it's missing some variables completely.

From the above issue:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ env.GITHUB_REF_SLUG }}
```

This raises the `Context access might be invalid` warning for `env.GITHUB_REF_SLUG`.

If the expression itself branches like so, only the ~"false"~ path as evaluated in the extension will raise a warning:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ true == false && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

Here, the warning will be raised again, but only for `env.GITHUB_REF_SLUG`.

If we "define" the env var in an `env` block explicitly:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        env:
          GITHUB_REF_SLUG: whatever
        run: echo ${{ true == false && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

then the warning goes away completely, and `env.FAKE_VAR` is never considered.

Alternatively, if we change the expression to something that can be evaluated as `true` at parse time:

```yaml
name: "Context access might be invalid"
on: push
jobs:
  context-access-might-be-invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        uses: rlespinasse/github-slug-action@v4

      - name: Print custom environment variables
        run: echo ${{ true && env.FAKE_VAR || env.GITHUB_REF_SLUG }}
```

Then the warning will change to `env.FAKE_VAR` only, ignoring the other one.

**To Reproduce**
See above.

**Expected behavior**
Both vars are warned against.

**Extension Version**
`v0.25.3`

**Comment by ad-m-ss** [comment] 2023-03-30 00:18
```
```
jobs:
  build-python-test:
    name: Build Python for test
    runs-on: ubuntu-20.04
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
```

Another instance is about `matrix` variable:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/99484706/228696386-71687918-801b-4213-a019-3c3cfe604f0f.png">

**Comment by cschleiden** [comment] 2023-03-31 18:07
@briantist Thanks for reporting this, I agree this is something we should look into. 

@ad-m-ss That is a valid error. The job isn't using a matrix strategy, so it won't be defined.

**Comment by cschleiden** [comment] 2023-04-05 23:06
This is fixed and will be included in the next release.

**Closed** 2023-04-05 23:06 UTC
Labels: bug

**Comment by DarlonHenrique** [comment] 2023-06-05 20:09
and they never fix it

**Comment by dev0T** [comment] 2023-06-07 21:46
> and they never fix it

It has been said it will be fixed in the next release.

**Comment by cschleiden** [comment] 2023-06-08 22:26
The release should've gone out by now. If you're still seeing things, would you mind creating another issue with more details? Thanks

**Comment by PhiFry** [comment] 2023-06-19 14:29
When is the release?

**Comment by VilotStar** [comment] 2023-06-20 00:15
I don't seem to have the release here either weirdly

**Comment by geekysaurabh001** [comment] 2023-11-08 11:34
Still seeing the same error in latest VSCode.

**Comment by klausbadelt** [comment] 2024-03-16 16:19
duplicate of #222
