### ISSUE TITLE
Syntax highlighting for `run` block

### ISSUE THREAD

**Issue by scarf005** [github/vscode-github-actions#120] opened 2023-04-15 03:09 UTC
**Is your feature request related to a problem? Please describe.**
Currently `run` block inside github actions are not syntax highlighted.

| Github Actions | Shell Script |
|--------|--------|
| ![ga][ga] | ![sh][sh] | 

**Describe the solution you'd like**
I'd love to see bash syntax highlight to be supported for `run` blocks.
the extension could detect [which shell a run block uses](https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory) then provide syntax highlight for it.

[ga]: https://github.com/github/vscode-github-actions/assets/54838975/be6bc162-3719-42e2-b506-a045a3a16c2d
[sh]: https://github.com/github/vscode-github-actions/assets/54838975/0c214aad-2211-4c63-846f-ae7b30666c07

**Comment by elbrenn** [comment] 2023-04-19 14:12
Thanks for the suggestion. This looks like a duplicate of https://github.com/github/vscode-github-actions/issues/114

**Closed by elbrenn** 2023-04-19 14:12 UTC
Labels: enhancement
