### ISSUE TITLE
Adding run name to workflow

### ISSUE THREAD

**Issue by nira40seas** [github/vscode-github-actions#241] opened 2023-08-02 18:01 UTC
**Is your feature request related to a problem? Please describe.**
When looking at the current branch runs, I can't identify each run as it doesn't present the name.
BTW, I looked at the code and I think it should have presented the name

**Describe the solution you'd like**
Present the name as is display in the website

**Additional context**
<img width="566" alt="Screenshot 2023-08-02 at 9 00 47 PM" src="https://github.com/github/vscode-github-actions/assets/109499767/011d7101-5fd0-417e-95a6-c75c95a10b74">
<img width="413" alt="Screenshot 2023-08-02 at 9 01 21 PM" src="https://github.com/github/vscode-github-actions/assets/109499767/a9b7ce90-dbb0-4555-937a-7f00c314f910">

**Comment by muzimuzhi** [comment] 2023-08-02 22:09
Similar:
- #90

**Comment by elbrenn** [comment] 2023-09-21 18:29
Closing as duplicate of https://github.com/github/vscode-github-actions/issues/90

**Closed by elbrenn** 2023-09-21 18:29 UTC
Labels: enhancement
