### ISSUE TITLE
No Github repositories found (MacOs)

### ISSUE THREAD

**Issue by pazfelipe** [github/vscode-github-actions#204] opened 2023-05-26 06:01 UTC
I tried to enable the Github actions extension on my VS Code but I always get the same message:

```
No Github repositories found.
Please open a folder that contains a Github repository
```

I have already tried [this](https://github.com/github/vscode-github-actions/issues/197) and [this](https://github.com/github/vscode-github-actions/issues/71) but none of these solutions worked for me.

I also tried with private and public repositories but even though it didn't work.

**Comment by felipesu19** [comment] 2023-05-26 14:38
Are you doing this on an installed version of vscode or the web editor? This is a known issue with the web editor.

**Comment by jtamsut** [comment] 2023-06-07 19:43
Going to close this since there hasn't been a response in two weeks. Feel free to re-open if this is still an issue. Thanks!

**Closed by jtamsut** 2023-06-07 19:43 UTC
Labels: bug

**Comment by mark-pictor-csec** [comment] 2023-06-20 21:59
I'm seeing this too, and not in the web editor. 
```
VSCode
Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z (6 days ago)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
```

I see a remote name config option `github-actions.remote-name`, and it is set correctly. I use ssh syntax in my `git remote` config so that different repos can use different git ssh keys; if the extension expects a particular syntax for the part of the url before the colon, this might be the cause. I'd hoped, since it's configured to expect `origin` to be github, that it would ignore everything before the colon.

`git remote -v show` reports something like
```
origin randomName:org/repo (fetch)
origin randomName:org/repo (push)
```
and the relevant ssh config entry is like
```
Host randomName
  Hostname github.com
  User git
  IdentityFile /path/to/key
#...
```

**Comment by mark-pictor-csec** [comment] 2023-06-20 22:08
@jtamsut mind re-opening?

**Comment by mark-pictor-csec** [comment] 2023-06-26 16:55
@jtamsut @felipesu19 mind re-opening? Or should I create a new issue?

**Comment by will-gendo** [comment] 2023-11-03 17:54
@mark-pictor-csec I'm experiencing the same issue due to what I assume is the same reason. I too use different hostnames in my ssh config file so that I can use different git accounts with different ssh keys. I would assume then that this extension checks only for `github.com` in the repository url?

@jtamsut @felipesu19 Could we reopen the issue?

**Comment by mark-pictor-csec** [comment] 2023-11-10 19:40
@will-gendo I'd forgotten to check back on this issue. Someone else opened #239, saving me the work :)
