### ISSUE TITLE
Update linting for secrets

### ISSUE THREAD

**Issue by ltaylorsbl** [github/vscode-github-actions#230] opened 2023-07-13 13:03 UTC
After installing the extension, I'm seeing some warnings in my workflow yaml file everytime I reference a secret. When I hover, the message says "Context access might be invalid."
![githubSecret](https://github.com/github/vscode-github-actions/assets/138524152/a96be822-6885-44eb-ab08-cdd6626bd896)

I think it's reasonable that it does this, but it would be nice if there weren't so many false positives (even if they are just warnings). In this case I have two ideas:
1. actually validate my secret name - since I signed in to GitHub, could it connect to my account and determine if the secret name is valid or not?
2. ignore the secret name and validate the syntax only - when the variable context is secret.<secret_name>, could the extension strictly look at the syntax to determine validity?

Thank you!

**Comment by KetchupOnMyKetchup** [comment] 2023-07-13 18:59
Actually this looks like a dupe of this - https://github.com/github/vscode-github-actions/issues/222

Closing this issue so we can track it all in one place. Thanks!

**Closed by KetchupOnMyKetchup** 2023-07-13 18:59 UTC
Labels: enhancement
