### ISSUE TITLE
Context access might be invalid: ACT

### ISSUE THREAD

**Issue by Zageron** [github/vscode-github-actions#67] opened 2023-03-30 05:39 UTC
**Describe the bug**
I believe this is a quality of life issue rather than a bug.
It would be nice for there to be a documented way, perhaps a quick actions, to ignore certain warnings.

The issue is that `if: ${{ !env.ACT }}` warns that ACT might be invalid. Which it will be when not running in an environment that defines ACT. Not sure if warning that an environment variable might not be declared is useful.

**To Reproduce**
1. Create any workflow block that contains an if statement referencing an environment variable that isn't declared in an env block.

**Expected behavior**
Either no warning, or a way to set particular environment variables to be ignored in this context.

**Screenshots**
![image](https://user-images.githubusercontent.com/1892473/228739829-6a4824db-5deb-472e-bd22-6a5f3edfe326.png)

**Extension Version**
`v0.25.3`

**Comment by Zageron** [comment] 2023-03-30 05:51
After further searching, appears to be a duplicate of both #61 and #47

**Comment by janaka** [comment] 2023-05-01 20:08
I'm also experiencing this issue. It makes no sense to me that this warning is being issued. Either the extension can validate all context or if it cannot do some then don't do any. Given that variables and secrets are viewable on the left I would imagine  if can validate.

Not sure if this is the cause but the workflow doesn't show in the left pane either.

**Comment by tylerclark** [comment] 2023-05-06 16:36
Fixed in next release: https://github.com/github/vscode-github-actions/issues/61#issuecomment-1498265231

**Closed** 2023-05-15 16:09 UTC
Labels: bug

**Comment by floehopper** [comment] 2023-07-04 20:44
@tylerclark:

> Fixed in next release: [#61 (comment)](https://github.com/github/vscode-github-actions/issues/61#issuecomment-1498265231)

I can't see a commit which fixes this - even an unreleased one. Where did you see it was fixed?

**Comment by wtachau** [comment] 2023-07-06 21:16
Still seeing this issue FYI

**Comment by elviskahoro** [comment] 2023-07-09 07:41
I'm also still seeing this!

**Comment by 80rian** [comment] 2023-07-10 05:29
definitely not fixed in the latest version.

**Comment by marcospgp** [comment] 2023-07-14 17:40
I would love to have no yellow underline on my workflow files :)

**Comment by brunokloss** [comment] 2023-07-18 21:06
i'm almost disabling the extension... problem showing in v.0.25.8 here too :(

**Comment by matlads** [comment] 2023-07-21 06:07
I am disabling the extension for now. i'll check back in about 5 months 😞

**Comment by Zageron** [comment] 2023-07-21 15:54
@felipesu19 @cschleiden
Ya'll are posting in a closed issue, no one is going to see this. Pinging for visibility.

**Comment by cschleiden** [comment] 2023-07-21 17:18
Have you tried declaring `ACT` as an environment variable? Something like 

```yaml
name: Demo workflow

env:
  ACT:

on:
  push:
  workflow_dispatch:
    inputs:
      name:
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello ${{ env.ACT }}"
```

**Comment by PrimeTimeTran** [comment] 2023-07-29 18:35
I uninstalled and reinstalled and then the warnings went away for me.

**Comment by epreston** [comment] 2023-08-06 04:36
> Have you tried declaring ACT as an environment variable? Something like

That does not fix the issue.  The "secrets" object is a simple dictionary of name / value pairs.  Is it possible to add a config section for what we expect the object to look like ?

**Comment by epreston** [comment] 2023-08-07 18:57
No. The issue is being able to add custom values.

It's good that it already has the values from the documentation.

**Comment by epreston** [comment] 2023-08-07 19:03
So unless we only use the prepopulated attributes on `secrets` or `env`, our scripts are filled with error warnings. The purpose of these objects is to extend them.  

A way to add known values to the shape of these objects, like adding words to a spell checker, would resolve this issue.

**Comment by cschleiden** [comment] 2023-08-07 22:47
It uses the actual secrets configured for the repository, not just from the documentation.

**Comment by epreston** [comment] 2023-08-07 22:49
Possible issue with that feature.  What's the best way for me to help ?  How can I generate a reproduction ?

**Comment by epreston** [comment] 2023-08-07 22:56
One reproduction would be following the steps from https://app.codecov.io/

They have you create a:

```
secrets.CODECOV_TOKEN
```

Then when you go to edit that .yml file, it will always show this error where `CODECOV_TOKEN` is used.

<img width="696" alt="issue" src="https://github.com/github/vscode-github-actions/assets/347224/b033cab7-ba9c-484f-b781-b31adfb21862">

Other plugins, like the spell checker, allow us to add words to the workspace settings to resolve similar issues.

**Comment by epreston** [comment] 2023-08-07 22:59
I can confirm this works and is populated in github and that the plugin has no knowledge of the secrets configured for the repository.

**Comment by Zageron** [comment] 2023-08-07 23:54
It would be a very impressive feature to have GH aware context. Just the keys mind you, values would not be good.

**Comment by cschleiden** [comment] 2023-08-08 17:17
@Zageron that is supported by the extension:

![CleanShot 2023-08-08 at 10 15 54@2x](https://github.com/github/vscode-github-actions/assets/2201819/bb082043-8063-4327-9d50-9afe4c00133e)

**Comment by cschleiden** [comment] 2023-08-08 22:25
Nothing, just login and open the repository.

**Comment by epreston** [comment] 2023-08-08 22:27
Since those Azure ones are well known and might be populated by the plugin staticly, could you create a secret named `CODECOV_TOKEN` and see if it appears in the list and allows it without warning ?

Thank you kindly.

**Comment by petrgazarov** [comment] 2023-08-09 02:54
@epreston I had to uninstall/reinstall the extension for the secret names autocomplete to start working. Also, fixed the yellow underlines.

**Comment by AmrAhmedA** [comment] 2023-08-16 08:43
Any possible fix?

**Comment by jacobmassengill** [comment] 2023-08-22 19:04
> @epreston I had to uninstall/reinstall the extension for the secret names autocomplete to start working. Also, fixed the yellow underlines.

This resolved the issue for me, can't believe I didn't try this first myself 😑

**Comment by ahmadnassri** [comment] 2023-09-12 13:17
I think this issue need to be re-opened

**Comment by MarioLiebisch** [comment] 2023-10-27 10:24
Just installed the extension (0.26.2) and immediately stumbled over this, which is not helpful.

**Comment by mark-pictor-csec** [comment] 2023-11-10 19:55
If I restart vscode, these warnings go away until I open a file under `.github`. But the instant I open one, all the warnings come back.

In my case the underlying cause seems to be a lack of alias support (#239).
