### ISSUE TITLE
The linter warning for context access is opaque and doesn't convey enough information to be actionable

### ISSUE THREAD

**Issue by asilverman** [github/vscode-github-actions#175] opened 2023-05-04 19:44 UTC
**Describe the bug**

I recently adopted using the VS code Github actions extension into my workflow and I want to start by saying thank you so much for your efforts in this space. 
As I was exploring the linter and syntax highlighting capabilities of this solution with respect to my files I encountered an issue that I don't feel empowered to fix (see image below):

![image](https://github.com/github/vscode-github-actions/assets/9611108/72e6c428-f40d-4e59-80ad-3b9a7b126f00)

A couple of comments on my use-case:
- I have verified that the secrets are set at the repository scope 
![image](https://github.com/github/vscode-github-actions/assets/9611108/00365415-35b0-49ba-a276-822a40b0c8c7)

- The warning message is not clear, I am confused what is the actual warning, why its triggered and what can I do to mitigate it

**To Reproduce**
1. With this workflow https://github.com/Azure/bicep-types-az/blob/asilverman/publish-oci-artifact/.github/workflows/update-types.yml
2. Load it in the extension
3. See warning

**Expected behavior**
I expect the warning message to:
- Be informative about what is causing the warning
- Point me to some informational resource to learn more about the subject
- Provide suggestions on how to fix the problem

**Extension Version**
![image](https://github.com/github/vscode-github-actions/assets/9611108/d1084754-f431-4736-b39f-515b8dd4c4d9)

**Additional context**

**Comment by cmolina** [comment] 2023-05-04 22:58
The error is gone after I sign in to Github, and restart vscode. In any case, the error messages need some love.

**Comment by tn3rb** [comment] 2023-05-09 17:17
I was experiencing the same issue with valid secrets being marked as warnings, and can confirm that restarting VS Code fixes the issue. 

Maybe a restart should be required after activation to avoid this confusion in the future.

Would also like to thank everyone for their time, effort, and talent with regards to creating this extension.

**Comment by alexhail** [comment] 2023-05-11 19:29
> The error is gone after I sign in to Github, and restart vscode. In any case, the error messages need some love.

This is the correct answer and should be marked as such for anyone searching for this bug after installing the extension from within VS Code. The signing into GitHub before the restart is the crucial step. Thank you!

**Comment by felipesu19** [comment] 2023-05-15 20:07
Since the issue is resolved, I'm going to close it, if we see people running into this in the future or it reoccurs, we'll investigate further. 

Thanks for opening this issue, and we really appreciate the kind words 👍

**Closed by felipesu19** 2023-05-15 20:07 UTC
Labels: bug
