### ISSUE TITLE
if conditional marked as error when using double single quote in an expression

### ISSUE THREAD

**Issue by sqin2019** [github/vscode-github-actions#211] opened 2023-06-06 20:12 UTC
**Describe the bug**
Below if conditional expression is marked as error, but the workflow actually runs as expected.
```
    if: '${{ github.event.review.state == ''approved'' }}'

```
error
```
"Unexpected symbol: 'approved'''. Located at position 32 within expression: github.event.review.state == ''approved''" 
```
**To Reproduce**
add condition:  if: '${{ github.event.review.state == ''approved'' }}'

**Expected behavior**
Not marked as error. As the additional single quote is to escape the literal single quote.

**Screenshots**
<img width="909" alt="Screenshot 2023-06-06 at 1 01 55 PM" src="https://github.com/github/vscode-github-actions/assets/51539171/e9ded13c-51be-4c95-ae56-6c6326788d32">

**Extension Version**
`v0.25.7`

**Additional context**

**Comment by jtamsut** [comment] 2023-06-07 19:29
We are aware of this issue. This is a duplicate of https://github.com/github/vscode-github-actions/issues/60. Going to close this.

**Closed by jtamsut** 2023-06-07 19:29 UTC
Labels: bug
