### ISSUE TITLE
Possibility to connect to github entreprise

### ISSUE THREAD

**Issue by edelanghe-ledger** [github/vscode-github-actions#63] opened 2023-03-29 15:38 UTC
We are using github enterprise internally and I would like to use this extension with it.

It could be great to select which remote url to use or better detect it from the git remote name.

github/vscode-pull-request-github did it here: https://github.com/microsoft/vscode-pull-request-github/issues/1793

**Comment by cschleiden** [comment] 2023-03-29 17:45
This is a dupe of #12

**Closed by cschleiden** 2023-03-29 17:45 UTC
Labels: enhancement
